<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="category">
	<div class="well">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

        <div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('category[order]', $category->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Sorting order'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => $new,
        'add' => 'Forum:Admin:Category@addAction',
        'edit' => 'Forum:Admin:Category@editAction',
        'save' => 'Forum:Admin:Category@saveAction',
        'cancel' => 'Forum:Admin:Browser@indexAction'
    )); ?>

</form>
