<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="post">
	<div class="well">
        <?php echo Element::hidden('post[id]', $post->getId()); ?>

        <div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('post[title]', $post->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Post name'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

        <div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::number('post[order]', $post->getOrder(), array('min' => 0, 'class' => 'form-control', 'placeholder' => $this->translate('Sorting order'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Topic'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('post[topic_id]', $topics, $post->getTopicId(), array('class' => 'form-control')); ?>
			</div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => $new,
        'add' => 'Forum:Admin:Post@addAction',
        'edit' => 'Forum:Admin:Post@editAction',
        'save' => 'Forum:Admin:Post@saveAction',
        'cancel' => 'Forum:Admin:Browser@indexAction'
    )); ?>

</form>
