<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="topic">
	<div class="well">
        <?php echo Element::hidden('topic[id]', $topic->getId()); ?>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('topic[name]', $topic->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Topic name'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('topic[category_id]', $categories, $topic->getCategoryId(), array('class' => 'form-control')); ?>
			</div>
        </div>

        <div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('topic[order]', $topic->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Sorting order'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => $new,
        'add' => 'Forum:Admin:Topic@addAction',
        'edit' => 'Forum:Admin:Topic@editAction',
        'save' => 'Forum:Admin:Topic@saveAction',
        'cancel' => 'Forum:Admin:Browser@indexAction'
    )); ?>

</form>
